import {
    BufferAttribute,
    BufferGeometry,
    Camera,
    OrthographicCamera,
    Points,
    PointsMaterial,
    Scene,
    WebGLRenderer
} from "three";
import FaceMeshCalculator from "./FaceMeshCalculator";
import ResourceTracker from "./ResourceTracker";

/**
 * Renders video
 */
export default class VideoRenderer {
    videoElement: HTMLVideoElement
    scene: Scene
    camera: Camera
    renderer: WebGLRenderer
    renderId: number | null = null
    private isRunning: Boolean
    private readonly viewSize: number;
    private readonly aspectRatio: number;
    lastLoop = Date.now();
    private fpsOutput: HTMLParagraphElement;
    private frameSpecificResourceTracker: ResourceTracker;
    private faceMeshCalculator: FaceMeshCalculator;
    private latestFaceMesh: Float32Array;

    constructor(videoElement: HTMLVideoElement,
                outputElement: HTMLDivElement,
                fpsOutput: HTMLParagraphElement,
                viewSize = 900,
                width = 680,
                height = 480) {
        this.videoElement = videoElement;
        outputElement.innerHTML = "";
        this.fpsOutput = fpsOutput;
        this.viewSize = viewSize
        this.aspectRatio = 680 / 480
        this.renderer = new WebGLRenderer({alpha: true});
        this.renderer.setSize(width, height);
        outputElement.appendChild(this.renderer.domElement)
        this.scene = new Scene();
        this.camera = new OrthographicCamera(
            -this.aspectRatio * viewSize / 2,
            this.aspectRatio * viewSize / 2,
            viewSize / 2,
            -viewSize / 2,
            -1000,
            1000);
        this.faceMeshCalculator = new FaceMeshCalculator(this.updateFaceMesh, this.aspectRatio, this.viewSize)
        this.frameSpecificResourceTracker = new ResourceTracker()
    }

    /**
     * Call this to start the rendering
     */
    startRender = () => {
        if (!this.videoElement.srcObject) {
            console.error("HTML Video element has no source object.")
        }
        this.stopRender();
        this.isRunning = true
        this.faceMeshCalculator.send({image: this.videoElement})
        this.renderId = window.requestAnimationFrame(this.renderLoop)
    }

    /**
     * Call this to stop rendering, aka. clear the previously requested frame
     */
    stopRender() {
        this.isRunning = false
        if (this.renderId) {
            window.cancelAnimationFrame(this.renderId)
            this.renderId = null
        }
    }

    /**
     * This function renders the latest face mesh state, which is set by FaceMeshCalculator asynchronously.
     */
    private renderLoop = async () => {
        if (!this.isRunning) {
            return
        }
        const thisLoop = Date.now()
        const fps = 1000 / (thisLoop - this.lastLoop)
        this.lastLoop = thisLoop
        this.fpsOutput.innerText = `${fps.toFixed(0)} FPS`

        if (this.videoElement.readyState == 4) { // https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/readyState
            this.scene.remove.apply(this.scene, this.scene.children)
        }

        if (this.latestFaceMesh) {
            const geometry = new BufferGeometry()
            geometry.setAttribute('position', new BufferAttribute(this.latestFaceMesh, 3))
            // geometry.rotateZ(Math.PI)
            let material = new PointsMaterial({color: 0xFFFFFF, size: 2});
            const meshPoints = new Points(geometry, material)
            this.scene.add(meshPoints)
        }

        this.renderer.render(this.scene, this.camera);
        if (this.renderId) window.cancelAnimationFrame(this.renderId)
        this.renderId = window.requestAnimationFrame(this.renderLoop)

        // Memory management
        // this.frameSpecificResourceTracker.dispose()
        // this.frameSpecificResourceTracker.track(geometry)
        // this.frameSpecificResourceTracker.track(material)
        // this.frameSpecificResourceTracker.track(meshPoints)
    }

    /**
     * Update the face mesh state (in the three.js scene) in this class, which is used in the render loop.
     * @param faceMesh All face landmarks for 1 face in 1D: [x, y, z, x, y, z, ...],
     * generated by the MediaPipe FaceMesh library.
     */
    private updateFaceMesh = async (faceMesh: Float32Array) => {
        this.latestFaceMesh = faceMesh
        // Immediately ask for another face to be processed
        await this.faceMeshCalculator.send({image: this.videoElement})
    }

    dispose() {
        console.log("Disposing VideoRenderer now...")
        this.frameSpecificResourceTracker.dispose()
        this.renderer.dispose()
        this.stopRender()
        this.faceMeshCalculator.close()
    }
}
